### PR TITLE
Remap 'equals' to 'equalTo' to work around jsii limitation

### LINKED ISSUE #393: cdktf get fails with aws provider @3
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdktf 1.7
node v14.5.0
python 3.7.4

### Affected Resource(s)

Running cdktf get fails with a  jsii compilation error if the requested version of the aws provider is 3.5 or higher

### Debug Output

https://gist.github.com/andynelson/4e71605c24ce5e412bf0130aace02616

### Expected Behavior

I expected the provider to build (as it does when the version is set to `aws@~> 2.0` or `aws@ 3.4`

### Actual Behavior

jsii complains about the use of `equals` as a parameter in the aws_guardduty_filter resource declaration
(this was introduced in the aws provider at version 3.5 - using a fixed version at `aws@ 3.4` works

### Steps to Reproduce

1.  delete the imports/aws directory
2. add `aws@~>3.0` to "terraformProviders" in cdkt.json
3. run `cdktf get`

### Important Factoids

Nothing unusual - cdktf get works with @ 3.4

### References

https://github.com/terraform-providers/terraform-provider-aws/pull/10676

* #0000

### PR DESCRIPTION
**Pull request by jsteinich**
Fixes #393 

This just adds to the existing renaming block in order to handle the `equals` attribute used by `aws_guardduty_filter`.
Long term this will hopefully be handled in jsii, but that is proving to be a bigger project than expected, so work around to unblock aws provider v3.

### CODE REVIEW

**Comment by skorfmann** [comment]
Cool - #395 got merged 👍

**Comment by jsteinich** [comment]
@skorfmann rebase complete.

**Review by skorfmann — APPROVED** [review]
