### ISSUE TITLE
databricks provider generation issue

### ISSUE THREAD

**Issue by stikkireddy** [hashicorp/terraform-cdk#2522]
The Databricks Terraform Provider has a resource called resource_provider and it is causing typescript errors. 

  | providers/databricks/index.ts:46:13 - error TS2300: Duplicate identifier 'provider'.
  | 46 export * as provider from './provider';
  |                ~~~~~~~~
  | providers/databricks/index.ts:102:13 - error TS2300: Duplicate identifier 'provider'.
  | 102 export * as provider from './provider';

### Affected Resource(s)

(https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/provider)

Any suggestions is there a way to generate stubs from a local build.

**Comment by DanielMSchmidt** [comment]
Databricks is currently failing, we fixed this in https://github.com/hashicorp/terraform-cdk/pull/2504, but we are waiting on some more fixes for 0.15.1. to ship
